# .gitkraft.yml
project:
  name: devops-pet-project
  owner: your-gitkraft-username
  ci: jenkins
  repository: https://github.com/your-username/devops-pet-project

metrics:
  enable: true
  dora:
    - deployment_frequency
    - lead_time_for_changes
    - change_failure_rate
    - mean_time_to_restore
  cicd:
    - pipeline_duration
    - build_success_rate
    - test_coverage
