- hosts: target
  become: yes
  tasks:
        
    - name: Load backend image
      shell: podman load -i /home/ec2-user/ci-temp/backend.tar

    - name: Stop old backend
      shell: podman stop backend || true && podman rm backend || true

    - name: Run backend container
      shell: podman run -d --name backend -p 5000:5000 backend:latest

    - name: Load frontend image
      shell: podman load -i /home/ec2-user/ci-temp/frontend.tar

    - name: Stop old frontend
      shell: podman stop frontend || true && podman rm frontend || true

    - name: Run frontend container
      shell: podman run -d --name frontend -p 80:80 frontend:latest
